//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LincolnTest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class PresentKB : global::System.Configuration.ApplicationSettingsBase {
        
        private static PresentKB defaultInstance = ((PresentKB)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PresentKB())));
        
        public static PresentKB Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N")]
        public string NextTrial {
            get {
                return ((string)(this["NextTrial"]));
            }
            set {
                this["NextTrial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B")]
        public string PreviousTrial {
            get {
                return ((string)(this["PreviousTrial"]));
            }
            set {
                this["PreviousTrial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public string TrialStart {
            get {
                return ((string)(this["TrialStart"]));
            }
            set {
                this["TrialStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Escape")]
        public string EndTrial {
            get {
                return ((string)(this["EndTrial"]));
            }
            set {
                this["EndTrial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public string AttentionImage {
            get {
                return ((string)(this["AttentionImage"]));
            }
            set {
                this["AttentionImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q")]
        public string AttentionSound {
            get {
                return ((string)(this["AttentionSound"]));
            }
            set {
                this["AttentionSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P")]
        public string AutoPlay {
            get {
                return ((string)(this["AutoPlay"]));
            }
            set {
                this["AutoPlay"] = value;
            }
        }
    }
}
